[REF] account_multicurrency_revaluation: Set the revaluation date on …
OCA/account-closing pull request #100
Opened 2019-01-24 15:18 UTC by keylor2906

…the context when calling the revaluate_currency method on the wizard view, to correctly use the rate of the input date, because without this change, the rate used for the creation of the move and lines would be of the day of creation and not of the required date.

2019-01-24 15:25 UTC, moylop260 approved these changes
:+1:
Just sign the CLA, please

2019-01-24 15:27 UTC, moylop260 commented
@grindtildeath @mpanarin
What do you think about?

2019-01-24 15:51 UTC, fclementic2c commented
Wow... That is a big problem. 
@grindtildeath can you have a look please ?

2019-01-29 22:39 UTC, grindtildeath requested changes
@keylor2906 I might be wrong but the revaluation date is used to set the context on the currency computation here : https://github.com/OCA/account-closing/blob/11.0/account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py#L140

Could this context key be missing somewhere ? In such case, can you please point where this context should be applied ?

In such case, would be great to add a test to highlight this change.

2019-01-30 17:38 UTC, keylor2906 commented
@grindtildeath 

The context would be needed here https://github.com/OCA/account-closing/blob/11.0/account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py#L311, so the rate returned here https://github.com/OCA/account-closing/blob/11.0/account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py#L150 would be of the date on the wizard and not date of execute.
Also needed for the rate of the account move line label https://github.com/OCA/account-closing/blob/11.0/account_multicurrency_revaluation/wizard/wizard_currency_revaluation.py#L327.

2019-01-30 22:01 UTC, grindtildeath commented
@keylor2906 Thanks for the explanation. 

Actually the returned rate is only used to format the label, so the computation was right but the label did show the wrong rate.

I opened #101 to fix this with a test, hope it's ok for you. :relaxed:

2019-01-30 22:05 UTC, keylor2906 commented
@grindtildeath Yes, I think it would be better to use https://github.com/OCA/account-closing/pull/101 instead of this fix.

2019-01-30 22:05 UTC, closed without merging