[IMP] Move the constraint on uniqueness for cutoff date at line level…
OCA/account-closing pull request #310
Opened 2024-11-14 13:43 UTC by lmarion-source

… + Add the possibility to create several cutoff with the same date

Business case can be :

- One user (A) creates a cutoff for some account moves. Another user (B) creates other moves, then wants to see those moves in a cutoff. However, B does not want to interfere with the cutoff A already made. B creates a new cutoff with the same date as the one of A, and when he generates lines, only retrieves the one that were not already in the cutoff of A.

- One user wants to create several cutoff at the same date, but for different journals/accounts

2024-11-14 16:01 UTC, jbaudoux requested changes
In my opinion, you cannot do such change because it has an impact on many other cutoff modules. Can't you leverage the user on cutoff entries instead of creating a separate new cutoff?

Side note: you should make one commit per module

2024-11-14 16:01 UTC, jbaudoux commented on account_cutoff_base/__manifest__.py
> +    "version": "16.0.1.0.1",
You cannot go backward

2024-11-22 13:35 UTC, acsonefho requested changes

2024-11-22 13:35 UTC, acsonefho commented on account_cutoff_base/migrations/16.0.1.0.1/post-migrate.py
> +        DROP CONSTRAINT account_cutoff_date_type_company_uniq
`IF EXISTS`

2024-11-27 13:17 UTC, acsonefho approved these changes

2025-05-04 12:23 UTC, closed without merging

2025-06-11 11:40 UTC, acsonefho commented
@OCA/accounting-maintainers Is it possible to re-open this one and review/merge?
It's already used in production for months :pray:

2025-06-11 12:57 UTC, jbaudoux commented
> @OCA/accounting-maintainers Is it possible to re-open this one and review/merge? It's already used in production for months 🙏

But I'm against this change. And there is no reply/follow-up to my comment

2025-06-11 13:07 UTC, rousseldenis commented
@lmarion-source @acsonefho @sbidoul Could you attend comments made by @jbaudoux ?

2025-06-11 13:13 UTC, lmarion-source commented
> @lmarion-source @acsonefho @sbidoul Could you attend comments made by @jbaudoux ?

On it :)