9.0 Port account_cutoff_base and account_cutoff_prepaid
OCA/account-closing pull request #37
Opened 2016-07-24 23:09 UTC by alexis-via

Extract a new module account_invoice_start_end_dates from account_cutoff_prepaid

Warning: it is not a port of the OCA/account-closing/8.0 version of the module, but a port of my LP branch https://code.launchpad.net/~akretion-team/account-closing/80-forecast-prepaid which is still the branch I use for Odoo v8 (which explains why I wasn't active on OCA/account-closing so far). This is due to the fact that my "forecast" branches were not merged on LP before the transition to github.

So the next step is to merge the few enhancements that took place in the OCA version of the module.

2016-07-24 23:34 UTC, alexis-via commented
And of course, this PR is also a port to the new API.

2016-10-03 22:07 UTC, alexis-via commented
@adrienpeiffer I don't see the pull request you told me about...

2016-10-07 19:42 UTC, adrienpeiffer approved these changes
:+1: Code review and functional test

2016-10-12 20:37 UTC, adrienpeiffer commented
@chrisdec do you have a moment to test it on runbot ? :smile:

2016-10-13 07:27 UTC, gurneyalex approved these changes
code review, no test.

2016-10-13 07:49 UTC, pedrobaeza requested changes
Several change across full code

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_base/models/account_cutoff.py
> +        '''Function designed to be inherited by other cutoff modules'''
Docstrings should use double triple-quota (applicable to all)

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_base/models/account_cutoff.py
> +        # add contre-partie
counter-part

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<data noupdate="1">
Put directly `<odoo noupdate="1">`

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_base/views/account_cutoff.xml
>  <data>
You can remove `<data>` tag

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_base/views/account_cutoff.xml
> +                        <field name="cutoff_journal_id" required="1"/>
Shouldn't this be put (required flag) at field level?

2016-10-13 07:49 UTC, pedrobaeza commented on account_cutoff_prepaid/i18n/account_cutoff_prepaid.pot
>  msgstr ""
Remove POT file

2016-10-13 07:49 UTC, pedrobaeza commented on account_invoice_start_end_dates/demo/product_demo.xml
> +<data>
Remove `<data>` tag

2016-10-13 07:49 UTC, pedrobaeza commented on account_invoice_start_end_dates/models/account_invoice.py
> +        '''Add start and end dates to hashcode used when the option "Group
Double quote

2016-10-13 08:14 UTC, alexis-via commented on account_cutoff_base/models/account_cutoff.py
> +        '''Function designed to be inherited by other cutoff modules'''
If docstring should really use double triple-quota, then why flake8/pylint says nothing about it ?

2016-10-13 08:47 UTC, chrisdec commented
Hello, 

Functional test : 

Just one note : is it possible to show the message "Don't forget to Re-Generate Lines after entering or leaving forecast mode." only when user actives or disables the checkbox "forecast"? It's quite confusing to have this message when you open a new prepaid expense or a new prepaid revenue.

Except that, 👍

2016-10-13 09:56 UTC, pedrobaeza commented on account_cutoff_base/models/account_cutoff.py
> +        '''Function designed to be inherited by other cutoff modules'''
Yes, good point. We need to add that check. But you can see here that what I say is correct: https://www.python.org/dev/peps/pep-0257/#id15 (`For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple-quoted strings""" . `)

2016-10-13 10:28 UTC, alexis-via commented on account_cutoff_base/views/account_cutoff.xml
> +                        <field name="cutoff_journal_id" required="1"/>
It is set at view level because it is inherited in the module account_cutoff_prepaid and replaced by attrs = {'required': [('forecast', '=', False)]}

2016-10-13 10:31 UTC, alexis-via commented
@chrisdec Yes, we need to find a better way. I guess a better way would be to use a button to enter/leave forecast mode (like the "Active" button on partners for example) and delete all lines when the user clicks on this button. I'll try to find time to do that...

2016-10-13 11:07 UTC, pedrobaeza commented on account_cutoff_base/views/account_cutoff.xml
> +                        <field name="cutoff_journal_id" required="1"/>
OK, thanks for the explanation. A comment in the XML would save this question for future readers of the code.

2016-10-17 10:19 UTC, pedrobaeza approved these changes

2016-10-17 10:19 UTC, merged