Migration of account_cutoff modules to 10.0
OCA/account-closing pull request #41
Opened 2016-10-17 09:51 UTC by adrienpeiffer

- [ ] Forward modification on https://github.com/OCA/account-closing/pull/37

2016-10-17 10:28 UTC, pedrobaeza requested changes

2016-10-17 10:28 UTC, pedrobaeza commented on setup/account_cutoff_base/.eggs/README.txt
> +This directory contains eggs that were downloaded by setuptools to build, test, and run plug-ins.
Why this file?

2016-10-17 10:28 UTC, pedrobaeza commented on setup/account_cutoff_base/odoo/addons/account_cutoff_base
> +../../../../account_cutoff_base
And these?

2016-10-17 15:51 UTC, Garamotte requested changes
I think you should split some big python files into one file per model.

2016-10-17 15:51 UTC, sylvain-garancher commented on account_cutoff_base/models/account_cutoff.py
> +    @api.depends('line_ids')
I think this field should also depend on `line_ids.cutoff_amount`.

2016-10-17 15:51 UTC, sylvain-garancher commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<odoo noupdate="1">
Is the change from `noupdate="0"` to `noupdate="1"` intentional ?

2016-10-17 15:51 UTC, sylvain-garancher commented on account_cutoff_prepaid/models/account_cutoff.py
> +        type = self._context.get('type')
Please avoid using python's reserved names as variable name.

2016-10-17 15:51 UTC, sylvain-garancher commented on account_cutoff_prepaid/models/account_cutoff.py
> +        type = self._context.get('type')
Please avoid using python's reserved names as variable name.

2016-10-17 15:51 UTC, sylvain-garancher commented on account_cutoff_prepaid/tests/test_account_cutoff_prepaid.py
> +        invoice.signal_workflow('invoice_open')
The workflow has been removed, you must use `invoice.action_invoice_open()` now.

2016-10-17 15:51 UTC, sylvain-garancher commented on account_invoice_start_end_dates/tests/test_invoice_start_end_dates.py
> +        invoice.signal_workflow('invoice_open')
The workflow has been removed, you must use `invoice.action_invoice_open()` now.

2016-10-18 06:53 UTC, adrienpeiffer commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<odoo noupdate="1">
This change is also in the version 9.0.
For me, record rules can be set as no updatable like it's done in Odoo core.
@alexis-via Any comment about this change ?

2016-10-18 06:56 UTC, pedrobaeza commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<odoo noupdate="1">
I agree. This way, you can set in your DB other rule if needed.

2016-10-18 06:59 UTC, adrienpeiffer commented on setup/account_cutoff_base/odoo/addons/account_cutoff_base
> +../../../../account_cutoff_base
This is the symlink to the module in the namespace package

2016-10-18 07:01 UTC, pedrobaeza commented on setup/account_cutoff_base/odoo/addons/account_cutoff_base
> +../../../../account_cutoff_base
But why is this now needed?

2016-10-18 07:09 UTC, sylvain-garancher commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<odoo noupdate="1">
Ok, no problem.
I asked because this could have been a typo.

2016-10-18 07:53 UTC, pedrobaeza approved these changes

2016-11-04 12:35 UTC, alexis-via commented on account_cutoff_base/security/account_cutoff_base_security.xml
> +<odoo noupdate="1">
yes, record rules should have noupdate="1"

2016-11-15 07:37 UTC, atchuthan approved these changes
Code review :+1: 
Tested functionality using PR https://github.com/OCA/sale-workflow/pull/357

2016-11-15 07:44 UTC, dvdhinesh approved these changes
Code :+1: 
Functional: account_invoice_start_end_dates :+1:

2016-11-15 07:58 UTC, pedrobaeza commented
Can you squash last 2 commits before merging?

2016-11-16 07:43 UTC, adrienpeiffer commented
@pedrobaeza it's done.

2016-11-16 08:50 UTC, merged