[MIG] account_cutoff_prepaid: Migration to 12.0
OCA/account-closing pull request #93
Opened 2018-12-21 12:34 UTC by jimhoefnagels

2018-12-21 12:39 UTC, jimhoefnagels commented
> Hey @jimhoefnagels, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet.
> You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla
> Here is a list of the users:
> 
>     * @jimhoefnagels (login unknown in OCA database)
> 
>     * oleksandrpaziuk [o.paziuk@mobilunity.com](mailto:o.paziuk@mobilunity.com) (no github login found)
> 
> 
> Appreciation of efforts,
> OCA CLAbot

CLA has been signed and sent for @jimhoefnagels on Mon, 17 Dec 2018

kind regards
Jim

2018-12-21 13:50 UTC, jimhoefnagels commented
Depends on PR89 and 90

2019-01-15 12:57 UTC, rven requested changes
Small code changes are needed to be conform the OCA requirements.

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/readme/CONTRIBUTORS.rst
> +* Jim Hoefnagels <jim.hoefnagels@dynapps.be>
Missing newline (missing-newline-extrafiles)
```suggestion
* Jim Hoefnagels <jim.hoefnagels@dynapps.be>

```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/readme/CONFIGURE.rst
> +* the *Default Account for Prepaid Expense*.
Missing newline (missing-newline-extrafiles)
```suggestion
* the *Default Account for Prepaid Expense*.

```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +        string='Forecast',
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +    start_date = fields.Date(string='Start Date')
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
    start_date = fields.Date()
```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +    end_date = fields.Date(string='End Date')
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
    end_date = fields.Date()
```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +    start_date = fields.Date(string='Start Date', readonly=True)
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
    start_date = fields.Date(readonly=True)
```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +    end_date = fields.Date(string='End Date', readonly=True)
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
    end_date = fields.Date(readonly=True)
```

2019-01-15 12:57 UTC, rven commented on account_cutoff_prepaid/models/account_cutoff.py
> +        string='Prepaid Days', readonly=True,
The attribute string is redundant. String parameter equal to name of variable (attribute-string-redundant)
```suggestion
        readonly=True,
```

2019-05-07 14:38 UTC, merged